#!/usr/bin/env python3
"""Generate SanjuOS capability data, documentation, and smoke expectations."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "capabilities/capabilities.toml"
RUST_OUTPUT = ROOT / "kernel/src/generated/capabilities.rs"
DOC_OUTPUT = ROOT / "docs/CAPABILITY_MATRIX.md"
SMOKE_OUTPUT = ROOT / "capabilities/smoke-expectations.txt"

STATUS_VARIANTS = {
    "planned": "Planned",
    "software_model": "SoftwareModel",
    "acceptance_prototype": "AcceptancePrototype",
    "hardware_active": "HardwareActive",
    "verified": "Verified",
}


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_registry() -> tuple[int, list[dict[str, object]]]:
    data = tomllib.loads(REGISTRY.read_text(encoding="utf-8"))
    version = int(data["registry_version"])
    entries = list(data.get("capability", []))
    seen: set[str] = set()
    for entry in entries:
        capability_id = str(entry["id"])
        if capability_id in seen:
            raise ValueError(f"duplicate capability id: {capability_id}")
        seen.add(capability_id)
        status = str(entry["status"])
        if status not in STATUS_VARIANTS:
            raise ValueError(f"unsupported status {status!r} for {capability_id}")
    return version, entries


def render_rust(version: int, entries: list[dict[str, object]]) -> str:
    lines = [
        "// @generated by scripts/generate-capabilities.py; do not edit.",
        "use crate::capabilities::{Capability, CapabilityStatus};",
        "",
        f"pub const REGISTRY_VERSION: u32 = {version};",
        "pub const CAPABILITIES: &[Capability] = &[",
    ]
    for entry in entries:
        status = STATUS_VARIANTS[str(entry["status"])]
        lines.extend(
            [
                "    Capability {",
                f"        id: {rust_string(str(entry['id']))},",
                f"        name: {rust_string(str(entry['name']))},",
                f"        status: CapabilityStatus::{status},",
                f"        milestone: {rust_string(str(entry['milestone']))},",
                f"        boot_label: {rust_string(str(entry.get('boot_label', '')))},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def render_docs(version: int, entries: list[dict[str, object]]) -> str:
    lines = [
        "# SanjuOS Capability Matrix",
        "",
        f"Registry version: **{version}**",
        "",
        "This file is generated from `capabilities/capabilities.toml`. Do not edit it manually.",
        "",
        "| ID | Capability | Status | Milestone | Evidence |",
        "|---|---|---|---|---|",
    ]
    for entry in entries:
        evidence = "<br>".join(f"`{item}`" for item in entry.get("evidence", []))
        lines.append(
            f"| `{entry['id']}` | {entry['name']} | `{entry['status']}` | "
            f"`{entry['milestone']}` | {evidence} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_smoke(entries: list[dict[str, object]]) -> str:
    lines = [
        "# @generated by scripts/generate-capabilities.py; one exact boot line per row.",
    ]
    lines.extend(
        str(entry["required_boot_line"])
        for entry in entries
        if entry.get("required_boot_line")
    )
    lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            print(f"generated file is stale: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    version, entries = load_registry()
    outputs = (
        (RUST_OUTPUT, render_rust(version, entries)),
        (DOC_OUTPUT, render_docs(version, entries)),
        (SMOKE_OUTPUT, render_smoke(entries)),
    )
    valid = all(write_or_check(path, content, args.check) for path, content in outputs)
    if valid:
        action = "verified" if args.check else "generated"
        print(f"SanjuOS capability registry {action}: {len(entries)} entries")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
